<%@ Page Language="C#" AutoEventWireup="true" CodeFile="deletecheque.aspx.cs" Inherits="invsterintrest_deletecheque" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .style1
        {
            width: 100%;
        }
        .style2
        {
            height: 45px;
            text-align: center;
            font-size: x-large;
            color: #000066;
        }
        .style3
        {
            height: 43px;
            text-align: right;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <table class="style1">
            <tr>
                <td bgcolor="#FF9933" class="style2">
                    <strong>PENDING DELETE CHEQUE</strong></td>
            </tr>
            <tr>
                <td class="style3">
                    <asp:Button ID="Button1" runat="server" Height="28px" onclick="Button1_Click" 
                        Text="DELETE ALL" Width="97px" 
                        style="margin-left: 0px; font-weight: 700; color: #FFFFFF;" 
                        BackColor="#003300" />
                </td>
            </tr>
            <tr>
                <td>
                                    <asp:GridView ID="GridView3" runat="server" Width="100%" 
                                        AutoGenerateDeleteButton="True"  DataKeyNames="ID"  onrowdeleting="GridView3_RowDeleting" AutoGenerateColumns="False" 
                                        BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" 
                                        CellPadding="4">
                                        <Columns>
                                         <asp:TemplateField HeaderText="ID">                             
                            <ItemTemplate>  
                                <asp:Label ID="ID" runat="server" Text='<%# Bind("ID") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="CUSTREGNO">                             
                            <ItemTemplate>  
                                <asp:Label ID="ID5" runat="server" Text='<%# Bind("CUSTREGNO") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>
                            <asp:TemplateField HeaderText="NAME">                             
                            <ItemTemplate>  
                                <asp:Label ID="ID6" runat="server" Text='<%# Bind("NAME") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>
                           <asp:TemplateField HeaderText="ARAZI">                             
                            <ItemTemplate>  
                                <asp:Label ID="ID7" runat="server" Text='<%# Bind("ARAZI") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="PLOT NO">                             
                            <ItemTemplate>  
                                <asp:Label ID="ID8" runat="server" Text='<%# Bind("PLOTNO") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>
                         <asp:TemplateField HeaderText="PLOT SIZE">                             
                            <ItemTemplate>  
                                <asp:Label ID="ID9" runat="server" Text='<%# Bind("PLOTSIZE") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="DATE">  
                            
                            <ItemTemplate>  
                                <asp:Label ID="CHEQUENODATE" runat="server" Text='<%# Bind("CDATE","{0:dd, MMM yyyy}") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>
                                          <asp:TemplateField HeaderText="CHEQUE NO.">  
                            
                            <ItemTemplate>  
                                <asp:Label ID="CHEQUENO0" runat="server" Text='<%# Bind("CHEQUENO") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>
                         <asp:TemplateField HeaderText="AMOUNT">  
                            
                            <ItemTemplate>  
                                <asp:Label ID="CAMOUNT0" runat="server" Text='<%# Bind("CAMOUNT") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>
                                         <asp:TemplateField HeaderText="CHEQUE TYPE">  
                              
                                
                            <ItemTemplate>  
                                <asp:Label ID="Label488" runat="server" Text='<%# Bind("CHEQUETYPE") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>  
                        <asp:TemplateField HeaderText="STATUS">  
                            
                            <ItemTemplate>  
                                <asp:Label ID="Label4888" runat="server" Text='<%# Bind("STATUS") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 
                        <asp:TemplateField HeaderText="DELETE">  
                             
                            <ItemTemplate>  
                                <asp:Label ID="CPAID0" runat="server" 
                                    Text='<%# Bind("deletevalue") %>'>  
                                </asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 
                                        </Columns>
                                        <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
                                        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
                                        <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
                                        <RowStyle BackColor="White" ForeColor="#330099" />
                                        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
                                        <SortedAscendingCellStyle BackColor="#FEFCEB" />
                                        <SortedAscendingHeaderStyle BackColor="#AF0101" />
                                        <SortedDescendingCellStyle BackColor="#F6F0C0" />
                                        <SortedDescendingHeaderStyle BackColor="#7E0000" />
                                    </asp:GridView>
                                </td>
            </tr>
            <tr>
                <td>
                    &nbsp;</td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
